/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yuehai_android_search_jni_MyJniTest */

#ifndef _Included_com_yuehai_android_search_jni_MyJniTest
#define _Included_com_yuehai_android_search_jni_MyJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yuehai_android_search_jni_MyJniTest
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yuehai_android_search_jni_MyJniTest_getName__
        (JNIEnv *, jobject);

/*
 * Class:     com_yuehai_android_search_jni_MyJniTest
 * Method:    getName2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yuehai_android_search_jni_MyJniTest_getName2__Ljava_lang_String_2
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
